//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace WebGather.Model
{
    /// <summary>
    /// 实体类Alibaba_ProGather。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Alibaba_ProGather")]
    [Serializable]
    public partial class Alibaba_ProGather : Entity
    {
        #region Model
        private int _ID;
        private int? _CompanyId;
        private string _ProductUrl;
        private long? _AliProductId;
        private long? _AliGroupId;
        private int? _Tag;
        private DateTime? _InsertTime;
        private int? _MogoutId;
        private int? _Grade;

        /// <summary>
        /// 
        /// </summary>
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? CompanyId
        {
            get { return _CompanyId; }
            set
            {
                this.OnPropertyValueChange("CompanyId");
                this._CompanyId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ProductUrl
        {
            get { return _ProductUrl; }
            set
            {
                this.OnPropertyValueChange("ProductUrl");
                this._ProductUrl = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public long? AliProductId
        {
            get { return _AliProductId; }
            set
            {
                this.OnPropertyValueChange("AliProductId");
                this._AliProductId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public long? AliGroupId
        {
            get { return _AliGroupId; }
            set
            {
                this.OnPropertyValueChange("AliGroupId");
                this._AliGroupId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Tag
        {
            get { return _Tag; }
            set
            {
                this.OnPropertyValueChange("Tag");
                this._Tag = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? InsertTime
        {
            get { return _InsertTime; }
            set
            {
                this.OnPropertyValueChange("InsertTime");
                this._InsertTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? MogoutId
        {
            get { return _MogoutId; }
            set
            {
                this.OnPropertyValueChange("MogoutId");
                this._MogoutId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Grade
        {
            get { return _Grade; }
            set
            {
                this.OnPropertyValueChange("Grade");
                this._Grade = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.CompanyId,
                _.ProductUrl,
                _.AliProductId,
                _.AliGroupId,
                _.Tag,
                _.InsertTime,
                _.MogoutId,
                _.Grade,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._CompanyId,
                this._ProductUrl,
                this._AliProductId,
                this._AliGroupId,
                this._Tag,
                this._InsertTime,
                this._MogoutId,
                this._Grade,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Alibaba_ProGather");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "Alibaba_ProGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CompanyId = new Field("CompanyId", "Alibaba_ProGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProductUrl = new Field("ProductUrl", "Alibaba_ProGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AliProductId = new Field("AliProductId", "Alibaba_ProGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AliGroupId = new Field("AliGroupId", "Alibaba_ProGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Tag = new Field("Tag", "Alibaba_ProGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "Alibaba_ProGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MogoutId = new Field("MogoutId", "Alibaba_ProGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Grade = new Field("Grade", "Alibaba_ProGather", "");
        }
        #endregion
    }
}