//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace WebGather.Model
{
    /// <summary>
    /// 实体类Alibaba_CompanyGather。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Alibaba_CompanyGather")]
    [Serializable]
    public partial class Alibaba_CompanyGather : Entity
    {
        #region Model
        private int _ID;
        private string _CompanyUrl;
        private int? _Tag;
        private int? _PageCount;
        private int? _CurrentPage;
        private DateTime? _InsertTime;
        private int? _ClassId;
        private string _ClassParPath;
        private int? _Grade;
        private int? _tagNew;
        private string _Country;
        private string _WebSite;

        /// <summary>
        /// 
        /// </summary>
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CompanyUrl
        {
            get { return _CompanyUrl; }
            set
            {
                this.OnPropertyValueChange("CompanyUrl");
                this._CompanyUrl = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Tag
        {
            get { return _Tag; }
            set
            {
                this.OnPropertyValueChange("Tag");
                this._Tag = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? PageCount
        {
            get { return _PageCount; }
            set
            {
                this.OnPropertyValueChange("PageCount");
                this._PageCount = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? CurrentPage
        {
            get { return _CurrentPage; }
            set
            {
                this.OnPropertyValueChange("CurrentPage");
                this._CurrentPage = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? InsertTime
        {
            get { return _InsertTime; }
            set
            {
                this.OnPropertyValueChange("InsertTime");
                this._InsertTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? ClassId
        {
            get { return _ClassId; }
            set
            {
                this.OnPropertyValueChange("ClassId");
                this._ClassId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ClassParPath
        {
            get { return _ClassParPath; }
            set
            {
                this.OnPropertyValueChange("ClassParPath");
                this._ClassParPath = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Grade
        {
            get { return _Grade; }
            set
            {
                this.OnPropertyValueChange("Grade");
                this._Grade = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? tagNew
        {
            get { return _tagNew; }
            set
            {
                this.OnPropertyValueChange("tagNew");
                this._tagNew = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Country
        {
            get { return _Country; }
            set
            {
                this.OnPropertyValueChange("Country");
                this._Country = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string WebSite
        {
            get { return _WebSite; }
            set
            {
                this.OnPropertyValueChange("WebSite");
                this._WebSite = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.CompanyUrl,
                _.Tag,
                _.PageCount,
                _.CurrentPage,
                _.InsertTime,
                _.ClassId,
                _.ClassParPath,
                _.Grade,
                _.tagNew,
                _.Country,
                _.WebSite,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._CompanyUrl,
                this._Tag,
                this._PageCount,
                this._CurrentPage,
                this._InsertTime,
                this._ClassId,
                this._ClassParPath,
                this._Grade,
                this._tagNew,
                this._Country,
                this._WebSite,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Alibaba_CompanyGather");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "Alibaba_CompanyGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CompanyUrl = new Field("CompanyUrl", "Alibaba_CompanyGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Tag = new Field("Tag", "Alibaba_CompanyGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PageCount = new Field("PageCount", "Alibaba_CompanyGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CurrentPage = new Field("CurrentPage", "Alibaba_CompanyGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field InsertTime = new Field("InsertTime", "Alibaba_CompanyGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ClassId = new Field("ClassId", "Alibaba_CompanyGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ClassParPath = new Field("ClassParPath", "Alibaba_CompanyGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Grade = new Field("Grade", "Alibaba_CompanyGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field tagNew = new Field("tagNew", "Alibaba_CompanyGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Country = new Field("Country", "Alibaba_CompanyGather", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field WebSite = new Field("WebSite", "Alibaba_CompanyGather", "");
        }
        #endregion
    }
}