//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace WebGather.Model
{
    /// <summary>
    /// 实体类Alibaba_ProImages。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Alibaba_ProImages")]
    [Serializable]
    public partial class Alibaba_ProImages : Entity
    {
        #region Model
        private int _ID;
        private long? _Pid;
        private string _ProductName;
        private string _ImageUrl;
        private string _LocalImagePath;
        private bool? _IsDown;
        private int? _DownType;
        private DateTime? _DownLoadTime;
        private int? _Type;

        /// <summary>
        /// 
        /// </summary>
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public long? Pid
        {
            get { return _Pid; }
            set
            {
                this.OnPropertyValueChange("Pid");
                this._Pid = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ProductName
        {
            get { return _ProductName; }
            set
            {
                this.OnPropertyValueChange("ProductName");
                this._ProductName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ImageUrl
        {
            get { return _ImageUrl; }
            set
            {
                this.OnPropertyValueChange("ImageUrl");
                this._ImageUrl = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string LocalImagePath
        {
            get { return _LocalImagePath; }
            set
            {
                this.OnPropertyValueChange("LocalImagePath");
                this._LocalImagePath = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool? IsDown
        {
            get { return _IsDown; }
            set
            {
                this.OnPropertyValueChange("IsDown");
                this._IsDown = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? DownType
        {
            get { return _DownType; }
            set
            {
                this.OnPropertyValueChange("DownType");
                this._DownType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? DownLoadTime
        {
            get { return _DownLoadTime; }
            set
            {
                this.OnPropertyValueChange("DownLoadTime");
                this._DownLoadTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Type
        {
            get { return _Type; }
            set
            {
                this.OnPropertyValueChange("Type");
                this._Type = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.Pid,
                _.ProductName,
                _.ImageUrl,
                _.LocalImagePath,
                _.IsDown,
                _.DownType,
                _.DownLoadTime,
                _.Type,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._Pid,
                this._ProductName,
                this._ImageUrl,
                this._LocalImagePath,
                this._IsDown,
                this._DownType,
                this._DownLoadTime,
                this._Type,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Alibaba_ProImages");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "Alibaba_ProImages", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Pid = new Field("Pid", "Alibaba_ProImages", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProductName = new Field("ProductName", "Alibaba_ProImages", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ImageUrl = new Field("ImageUrl", "Alibaba_ProImages", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field LocalImagePath = new Field("LocalImagePath", "Alibaba_ProImages", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IsDown = new Field("IsDown", "Alibaba_ProImages", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DownType = new Field("DownType", "Alibaba_ProImages", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DownLoadTime = new Field("DownLoadTime", "Alibaba_ProImages", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Type = new Field("Type", "Alibaba_ProImages", "");
        }
        #endregion
    }
}