//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace WebGather.Model
{
    /// <summary>
    /// 实体类Alibaba_CompanyInfo。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Alibaba_CompanyInfo")]
    [Serializable]
    public partial class Alibaba_CompanyInfo : Entity
    {
        #region Model
        private int _id;
        private string _CompanyUrl;
        private int? _Tag;
        private int? _PageCount;
        private int? _CurrentPage;
        private string _CompanyName;
        private string _CompanyLogo;
        private bool? _IsVerify;
        private string _VerifyInfo;
        private string _VerifyGroup;
        private string _VerifyLogo;
        private string _BusinessType;
        private string _Location;
        private string _Top1Market;
        private string _Top2Market;
        private string _Top3Market;
        private string _Ownership;
        private string _NumberOfEmployees;
        private string _TotalAnnualSalesVolume;
        private string _EstablishedYear;
        private string _MainProducts;
        private string _Certifications;
        private string _ProductCertifications;
        private string _FactorySize;
        private string _FactoryLocation;
        private string _NumberOfProductionLines;
        private string _ContractManufacturing;
        private string _AnnualOutputValue;
        private string _ContactName;
        private string _ContactLogo;
        private string _ContactDepartment;
        private string _ContactJobTitle;
        private string _Telephone;
        private string _MobilePhone;
        private string _Fax;
        private string _Address;
        private string _Zip;
        private string _CountryRegion;
        private string _ProvinceState;
        private string _City;
        private string _OperationalAddress;
        private string _Website;
        private DateTime? _AddTime;
        private bool? _IsGather;

        /// <summary>
        /// 
        /// </summary>
        public int id
        {
            get { return _id; }
            set
            {
                this.OnPropertyValueChange("id");
                this._id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CompanyUrl
        {
            get { return _CompanyUrl; }
            set
            {
                this.OnPropertyValueChange("CompanyUrl");
                this._CompanyUrl = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Tag
        {
            get { return _Tag; }
            set
            {
                this.OnPropertyValueChange("Tag");
                this._Tag = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? PageCount
        {
            get { return _PageCount; }
            set
            {
                this.OnPropertyValueChange("PageCount");
                this._PageCount = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? CurrentPage
        {
            get { return _CurrentPage; }
            set
            {
                this.OnPropertyValueChange("CurrentPage");
                this._CurrentPage = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CompanyName
        {
            get { return _CompanyName; }
            set
            {
                this.OnPropertyValueChange("CompanyName");
                this._CompanyName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CompanyLogo
        {
            get { return _CompanyLogo; }
            set
            {
                this.OnPropertyValueChange("CompanyLogo");
                this._CompanyLogo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool? IsVerify
        {
            get { return _IsVerify; }
            set
            {
                this.OnPropertyValueChange("IsVerify");
                this._IsVerify = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string VerifyInfo
        {
            get { return _VerifyInfo; }
            set
            {
                this.OnPropertyValueChange("VerifyInfo");
                this._VerifyInfo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string VerifyGroup
        {
            get { return _VerifyGroup; }
            set
            {
                this.OnPropertyValueChange("VerifyGroup");
                this._VerifyGroup = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string VerifyLogo
        {
            get { return _VerifyLogo; }
            set
            {
                this.OnPropertyValueChange("VerifyLogo");
                this._VerifyLogo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string BusinessType
        {
            get { return _BusinessType; }
            set
            {
                this.OnPropertyValueChange("BusinessType");
                this._BusinessType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Location
        {
            get { return _Location; }
            set
            {
                this.OnPropertyValueChange("Location");
                this._Location = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Top1Market
        {
            get { return _Top1Market; }
            set
            {
                this.OnPropertyValueChange("Top1Market");
                this._Top1Market = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Top2Market
        {
            get { return _Top2Market; }
            set
            {
                this.OnPropertyValueChange("Top2Market");
                this._Top2Market = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Top3Market
        {
            get { return _Top3Market; }
            set
            {
                this.OnPropertyValueChange("Top3Market");
                this._Top3Market = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Ownership
        {
            get { return _Ownership; }
            set
            {
                this.OnPropertyValueChange("Ownership");
                this._Ownership = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string NumberOfEmployees
        {
            get { return _NumberOfEmployees; }
            set
            {
                this.OnPropertyValueChange("NumberOfEmployees");
                this._NumberOfEmployees = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string TotalAnnualSalesVolume
        {
            get { return _TotalAnnualSalesVolume; }
            set
            {
                this.OnPropertyValueChange("TotalAnnualSalesVolume");
                this._TotalAnnualSalesVolume = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string EstablishedYear
        {
            get { return _EstablishedYear; }
            set
            {
                this.OnPropertyValueChange("EstablishedYear");
                this._EstablishedYear = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MainProducts
        {
            get { return _MainProducts; }
            set
            {
                this.OnPropertyValueChange("MainProducts");
                this._MainProducts = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Certifications
        {
            get { return _Certifications; }
            set
            {
                this.OnPropertyValueChange("Certifications");
                this._Certifications = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ProductCertifications
        {
            get { return _ProductCertifications; }
            set
            {
                this.OnPropertyValueChange("ProductCertifications");
                this._ProductCertifications = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string FactorySize
        {
            get { return _FactorySize; }
            set
            {
                this.OnPropertyValueChange("FactorySize");
                this._FactorySize = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string FactoryLocation
        {
            get { return _FactoryLocation; }
            set
            {
                this.OnPropertyValueChange("FactoryLocation");
                this._FactoryLocation = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string NumberOfProductionLines
        {
            get { return _NumberOfProductionLines; }
            set
            {
                this.OnPropertyValueChange("NumberOfProductionLines");
                this._NumberOfProductionLines = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ContractManufacturing
        {
            get { return _ContractManufacturing; }
            set
            {
                this.OnPropertyValueChange("ContractManufacturing");
                this._ContractManufacturing = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string AnnualOutputValue
        {
            get { return _AnnualOutputValue; }
            set
            {
                this.OnPropertyValueChange("AnnualOutputValue");
                this._AnnualOutputValue = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ContactName
        {
            get { return _ContactName; }
            set
            {
                this.OnPropertyValueChange("ContactName");
                this._ContactName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ContactLogo
        {
            get { return _ContactLogo; }
            set
            {
                this.OnPropertyValueChange("ContactLogo");
                this._ContactLogo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ContactDepartment
        {
            get { return _ContactDepartment; }
            set
            {
                this.OnPropertyValueChange("ContactDepartment");
                this._ContactDepartment = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ContactJobTitle
        {
            get { return _ContactJobTitle; }
            set
            {
                this.OnPropertyValueChange("ContactJobTitle");
                this._ContactJobTitle = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Telephone
        {
            get { return _Telephone; }
            set
            {
                this.OnPropertyValueChange("Telephone");
                this._Telephone = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MobilePhone
        {
            get { return _MobilePhone; }
            set
            {
                this.OnPropertyValueChange("MobilePhone");
                this._MobilePhone = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Fax
        {
            get { return _Fax; }
            set
            {
                this.OnPropertyValueChange("Fax");
                this._Fax = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Address
        {
            get { return _Address; }
            set
            {
                this.OnPropertyValueChange("Address");
                this._Address = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Zip
        {
            get { return _Zip; }
            set
            {
                this.OnPropertyValueChange("Zip");
                this._Zip = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CountryRegion
        {
            get { return _CountryRegion; }
            set
            {
                this.OnPropertyValueChange("CountryRegion");
                this._CountryRegion = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ProvinceState
        {
            get { return _ProvinceState; }
            set
            {
                this.OnPropertyValueChange("ProvinceState");
                this._ProvinceState = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string City
        {
            get { return _City; }
            set
            {
                this.OnPropertyValueChange("City");
                this._City = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string OperationalAddress
        {
            get { return _OperationalAddress; }
            set
            {
                this.OnPropertyValueChange("OperationalAddress");
                this._OperationalAddress = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Website
        {
            get { return _Website; }
            set
            {
                this.OnPropertyValueChange("Website");
                this._Website = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? AddTime
        {
            get { return _AddTime; }
            set
            {
                this.OnPropertyValueChange("AddTime");
                this._AddTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool? IsGather
        {
            get { return _IsGather; }
            set
            {
                this.OnPropertyValueChange("IsGather");
                this._IsGather = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.id,
                _.CompanyUrl,
                _.Tag,
                _.PageCount,
                _.CurrentPage,
                _.CompanyName,
                _.CompanyLogo,
                _.IsVerify,
                _.VerifyInfo,
                _.VerifyGroup,
                _.VerifyLogo,
                _.BusinessType,
                _.Location,
                _.Top1Market,
                _.Top2Market,
                _.Top3Market,
                _.Ownership,
                _.NumberOfEmployees,
                _.TotalAnnualSalesVolume,
                _.EstablishedYear,
                _.MainProducts,
                _.Certifications,
                _.ProductCertifications,
                _.FactorySize,
                _.FactoryLocation,
                _.NumberOfProductionLines,
                _.ContractManufacturing,
                _.AnnualOutputValue,
                _.ContactName,
                _.ContactLogo,
                _.ContactDepartment,
                _.ContactJobTitle,
                _.Telephone,
                _.MobilePhone,
                _.Fax,
                _.Address,
                _.Zip,
                _.CountryRegion,
                _.ProvinceState,
                _.City,
                _.OperationalAddress,
                _.Website,
                _.AddTime,
                _.IsGather,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._id,
                this._CompanyUrl,
                this._Tag,
                this._PageCount,
                this._CurrentPage,
                this._CompanyName,
                this._CompanyLogo,
                this._IsVerify,
                this._VerifyInfo,
                this._VerifyGroup,
                this._VerifyLogo,
                this._BusinessType,
                this._Location,
                this._Top1Market,
                this._Top2Market,
                this._Top3Market,
                this._Ownership,
                this._NumberOfEmployees,
                this._TotalAnnualSalesVolume,
                this._EstablishedYear,
                this._MainProducts,
                this._Certifications,
                this._ProductCertifications,
                this._FactorySize,
                this._FactoryLocation,
                this._NumberOfProductionLines,
                this._ContractManufacturing,
                this._AnnualOutputValue,
                this._ContactName,
                this._ContactLogo,
                this._ContactDepartment,
                this._ContactJobTitle,
                this._Telephone,
                this._MobilePhone,
                this._Fax,
                this._Address,
                this._Zip,
                this._CountryRegion,
                this._ProvinceState,
                this._City,
                this._OperationalAddress,
                this._Website,
                this._AddTime,
                this._IsGather,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Alibaba_CompanyInfo");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field id = new Field("id", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CompanyUrl = new Field("CompanyUrl", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Tag = new Field("Tag", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PageCount = new Field("PageCount", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CurrentPage = new Field("CurrentPage", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CompanyName = new Field("CompanyName", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CompanyLogo = new Field("CompanyLogo", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IsVerify = new Field("IsVerify", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field VerifyInfo = new Field("VerifyInfo", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field VerifyGroup = new Field("VerifyGroup", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field VerifyLogo = new Field("VerifyLogo", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field BusinessType = new Field("BusinessType", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Location = new Field("Location", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Top1Market = new Field("Top1Market", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Top2Market = new Field("Top2Market", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Top3Market = new Field("Top3Market", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Ownership = new Field("Ownership", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field NumberOfEmployees = new Field("NumberOfEmployees", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field TotalAnnualSalesVolume = new Field("TotalAnnualSalesVolume", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field EstablishedYear = new Field("EstablishedYear", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MainProducts = new Field("MainProducts", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Certifications = new Field("Certifications", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProductCertifications = new Field("ProductCertifications", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FactorySize = new Field("FactorySize", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field FactoryLocation = new Field("FactoryLocation", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field NumberOfProductionLines = new Field("NumberOfProductionLines", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ContractManufacturing = new Field("ContractManufacturing", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AnnualOutputValue = new Field("AnnualOutputValue", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ContactName = new Field("ContactName", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ContactLogo = new Field("ContactLogo", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ContactDepartment = new Field("ContactDepartment", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ContactJobTitle = new Field("ContactJobTitle", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Telephone = new Field("Telephone", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field MobilePhone = new Field("MobilePhone", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Fax = new Field("Fax", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Address = new Field("Address", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Zip = new Field("Zip", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CountryRegion = new Field("CountryRegion", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ProvinceState = new Field("ProvinceState", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field City = new Field("City", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field OperationalAddress = new Field("OperationalAddress", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Website = new Field("Website", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime", "Alibaba_CompanyInfo", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field IsGather = new Field("IsGather", "Alibaba_CompanyInfo", "");
        }
        #endregion
    }
}