//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace WebGather.Model
{
    /// <summary>
    /// 实体类Alibaba_ProClass。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Alibaba_ProClass")]
    [Serializable]
    public partial class Alibaba_ProClass : Entity
    {
        #region Model
        private int _ID;
        private int? _AlibabaID;
        private int? _ParID;
        private string _ParPath;
        private string _ClassName;
        private int? _Tag;
        private int? _PageCount;
        private int? _CurrentPage;
        private int? _DayCount;
        private int? _Grade;
        private int? _New_PCount;
        private int? _New_CPage;
        private int? _New_Tag;
        private DateTime? _New_Time;

        /// <summary>
        /// 
        /// </summary>
        public int ID
        {
            get { return _ID; }
            set
            {
                this.OnPropertyValueChange("ID");
                this._ID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? AlibabaID
        {
            get { return _AlibabaID; }
            set
            {
                this.OnPropertyValueChange("AlibabaID");
                this._AlibabaID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? ParID
        {
            get { return _ParID; }
            set
            {
                this.OnPropertyValueChange("ParID");
                this._ParID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ParPath
        {
            get { return _ParPath; }
            set
            {
                this.OnPropertyValueChange("ParPath");
                this._ParPath = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ClassName
        {
            get { return _ClassName; }
            set
            {
                this.OnPropertyValueChange("ClassName");
                this._ClassName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Tag
        {
            get { return _Tag; }
            set
            {
                this.OnPropertyValueChange("Tag");
                this._Tag = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? PageCount
        {
            get { return _PageCount; }
            set
            {
                this.OnPropertyValueChange("PageCount");
                this._PageCount = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? CurrentPage
        {
            get { return _CurrentPage; }
            set
            {
                this.OnPropertyValueChange("CurrentPage");
                this._CurrentPage = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? DayCount
        {
            get { return _DayCount; }
            set
            {
                this.OnPropertyValueChange("DayCount");
                this._DayCount = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Grade
        {
            get { return _Grade; }
            set
            {
                this.OnPropertyValueChange("Grade");
                this._Grade = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? New_PCount
        {
            get { return _New_PCount; }
            set
            {
                this.OnPropertyValueChange("New_PCount");
                this._New_PCount = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? New_CPage
        {
            get { return _New_CPage; }
            set
            {
                this.OnPropertyValueChange("New_CPage");
                this._New_CPage = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? New_Tag
        {
            get { return _New_Tag; }
            set
            {
                this.OnPropertyValueChange("New_Tag");
                this._New_Tag = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? New_Time
        {
            get { return _New_Time; }
            set
            {
                this.OnPropertyValueChange("New_Time");
                this._New_Time = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.ID,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.ID;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.ID,
                _.AlibabaID,
                _.ParID,
                _.ParPath,
                _.ClassName,
                _.Tag,
                _.PageCount,
                _.CurrentPage,
                _.DayCount,
                _.Grade,
                _.New_PCount,
                _.New_CPage,
                _.New_Tag,
                _.New_Time,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._ID,
                this._AlibabaID,
                this._ParID,
                this._ParPath,
                this._ClassName,
                this._Tag,
                this._PageCount,
                this._CurrentPage,
                this._DayCount,
                this._Grade,
                this._New_PCount,
                this._New_CPage,
                this._New_Tag,
                this._New_Time,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Alibaba_ProClass");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID", "Alibaba_ProClass", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field AlibabaID = new Field("AlibabaID", "Alibaba_ProClass", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ParID = new Field("ParID", "Alibaba_ProClass", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ParPath = new Field("ParPath", "Alibaba_ProClass", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ClassName = new Field("ClassName", "Alibaba_ProClass", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Tag = new Field("Tag", "Alibaba_ProClass", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field PageCount = new Field("PageCount", "Alibaba_ProClass", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field CurrentPage = new Field("CurrentPage", "Alibaba_ProClass", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field DayCount = new Field("DayCount", "Alibaba_ProClass", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Grade = new Field("Grade", "Alibaba_ProClass", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field New_PCount = new Field("New_PCount", "Alibaba_ProClass", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field New_CPage = new Field("New_CPage", "Alibaba_ProClass", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field New_Tag = new Field("New_Tag", "Alibaba_ProClass", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field New_Time = new Field("New_Time", "Alibaba_ProClass", "");
        }
        #endregion
    }
}