//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace WebGather.Model
{
    /// <summary>
    /// 实体类Sys_Error。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Sys_Error")]
    [Serializable]
    public partial class Sys_Error : Entity
    {
        #region Model
        private int _Id;
        private DateTime? _Date;
        private string _Thread;
        private string _Level;
        private string _Logger;
        private string _Source;
        private string _Message;

        /// <summary>
        /// 
        /// </summary>
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? Date
        {
            get { return _Date; }
            set
            {
                this.OnPropertyValueChange("Date");
                this._Date = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Thread
        {
            get { return _Thread; }
            set
            {
                this.OnPropertyValueChange("Thread");
                this._Thread = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Level
        {
            get { return _Level; }
            set
            {
                this.OnPropertyValueChange("Level");
                this._Level = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Logger
        {
            get { return _Logger; }
            set
            {
                this.OnPropertyValueChange("Logger");
                this._Logger = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Source
        {
            get { return _Source; }
            set
            {
                this.OnPropertyValueChange("Source");
                this._Source = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Message
        {
            get { return _Message; }
            set
            {
                this.OnPropertyValueChange("Message");
                this._Message = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.Date,
                _.Thread,
                _.Level,
                _.Logger,
                _.Source,
                _.Message,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._Date,
                this._Thread,
                this._Level,
                this._Logger,
                this._Source,
                this._Message,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Sys_Error");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Sys_Error", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Date = new Field("Date", "Sys_Error", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Thread = new Field("Thread", "Sys_Error", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Level = new Field("Level", "Sys_Error", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Logger = new Field("Logger", "Sys_Error", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Source = new Field("Source", "Sys_Error", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Message = new Field("Message", "Sys_Error", "");
        }
        #endregion
    }
}