//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;
using Dos.ORM.Common;

namespace WebGather.Model
{

    /// <summary>
    /// 实体类User_Info 。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("User_Info")]
    [Serializable]
    public partial class User_Info : Entity
    {
        #region Model
        private int _Id;
        private string _FirstName;
        private string _LastName;
        private bool? _Gender;
        private string _ContactPic;
        private string _UserName;
        private string _Psw;
        private string _Email;
        private string _Tel;
        private string _Fax;
        private string _Mobile;
        private string _WhatsApp;
        private string _Skype;
        private string _Department;
        private string _Job;
        private int? _Addr_CountryID;
        private string _Addr_Country;
        private int? _Addr_ProvinceID;
        private string _Addr_Province;
        private string _Addr_Street;
        private string _Address;
        private string _PostalCode;
        private string _Wp_Url;
        private int? _WP_TemplateID;
        private string _Wp_Config;
        private string _Wp_Banner;
        private string _CompanyName;
        private string _CompanyPic;
        private string _BusinessTypeID;
        private string _BusinessType;
        private string _ProductService_Sell;
        private string _ProductService_Buy;
        private int? _CompanyRegistered;
        private string _TotalEmployees;
        private string _Logo;
        private string _Introduction;
        private string _WebsiteUrl;
        private string _Brands;
        private string _LegalForm;
        private string _LegalOwner;
        private string _LegalCEO;
        private string _OperationalAddressType;
        private string _OwnershipType;
        private string _RegisteredCapital;
        private string _TotalAnnualSalesVolume;
        private string _TotalAnnualPurchaseVolume;
        private string _ExportPercentage;
        private string _MainMarkets;
        private string _MainCustomers;
        private string _TradeShows;
        private string _ContractManufacturing;
        private string _FactorySize;
        private string _FactoryLocation;
        private int? _BuiltYear;
        private string _ProductRange;
        private string _MonthlyCapacity;
        private string _QAQC;
        private string _NoofProductionLines;
        private string _NoofRDStaff;
        private string _NoofQCStaff;
        private string _ManagementCertification;
        private DateTime? _RegTime;
        private int? _LoginNums;
        private DateTime? _LoginTime;
        private string _LoginIp;
        private bool? _IsGather;
        private int? _UserType;
        private int? _Grade;
        private int? _Type;
        private int? _EmailStatus;
        private int? _WebsiteUrlStatus;
        private int? _ProductStatus;
        private int? _EditAdminId;
        private DateTime? _EditTime;
        private int? _Status;
        private int? _IndustryType;
        private int? _Stock_Id;
        private int? _AdminId;
        private int? _UserLevel;
        private int? _KeywordsNum;
        private int? _UsekeywordsNum;
        private int? _UserProductCount;
        private string _Certification;
        private string _Licence;
        private int? _BaseAuditedStatus;
        private string _BaseAuditedCode;
        private int? _ThirdPartyAuditedStatus;
        private string _ThirdPartyAuditedCode;
        private bool? _IsModified;
        private string _ModifyCode;
        private string _InfoCompletedCode;
        private DateTime? _AuditedTime;
        private DateTime? _CheckDate;
        private string _Reason;
        private float? _Boost;
        private float? _BoostOrder;
        private string _Contact_Address;
        private int? _InquiryLimit;
        private int? _InquiryLimitUse;
        private int? _GatherId;
        private string _ProductionFlowPic;
        /// <summary>
        /// 
        /// </summary>
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange(_.Id, _Id, value);
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string FirstName
        {
            get { return _FirstName; }
            set
            {
                this.OnPropertyValueChange(_.FirstName, _FirstName, value);
                this._FirstName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string LastName
        {
            get { return _LastName; }
            set
            {
                this.OnPropertyValueChange(_.LastName, _LastName, value);
                this._LastName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool? Gender
        {
            get { return _Gender; }
            set
            {
                this.OnPropertyValueChange(_.Gender, _Gender, value);
                this._Gender = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ContactPic
        {
            get { return _ContactPic; }
            set
            {
                this.OnPropertyValueChange(_.ContactPic, _ContactPic, value);
                this._ContactPic = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UserName
        {
            get { return _UserName; }
            set
            {
                this.OnPropertyValueChange(_.UserName, _UserName, value);
                this._UserName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Psw
        {
            get { return _Psw; }
            set
            {
                this.OnPropertyValueChange(_.Psw, _Psw, value);
                this._Psw = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Email
        {
            get { return _Email; }
            set
            {
                this.OnPropertyValueChange(_.Email, _Email, value);
                this._Email = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Tel
        {
            get { return _Tel; }
            set
            {
                this.OnPropertyValueChange(_.Tel, _Tel, value);
                this._Tel = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Fax
        {
            get { return _Fax; }
            set
            {
                this.OnPropertyValueChange(_.Fax, _Fax, value);
                this._Fax = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Mobile
        {
            get { return _Mobile; }
            set
            {
                this.OnPropertyValueChange(_.Mobile, _Mobile, value);
                this._Mobile = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string WhatsApp
        {
            get { return _WhatsApp; }
            set
            {
                this.OnPropertyValueChange(_.WhatsApp, _WhatsApp, value);
                this._WhatsApp = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Skype
        {
            get { return _Skype; }
            set
            {
                this.OnPropertyValueChange(_.Skype, _Skype, value);
                this._Skype = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Department
        {
            get { return _Department; }
            set
            {
                this.OnPropertyValueChange(_.Department, _Department, value);
                this._Department = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Job
        {
            get { return _Job; }
            set
            {
                this.OnPropertyValueChange(_.Job, _Job, value);
                this._Job = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Addr_CountryID
        {
            get { return _Addr_CountryID; }
            set
            {
                this.OnPropertyValueChange(_.Addr_CountryID, _Addr_CountryID, value);
                this._Addr_CountryID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Addr_Country
        {
            get { return _Addr_Country; }
            set
            {
                this.OnPropertyValueChange(_.Addr_Country, _Addr_Country, value);
                this._Addr_Country = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Addr_ProvinceID
        {
            get { return _Addr_ProvinceID; }
            set
            {
                this.OnPropertyValueChange(_.Addr_ProvinceID, _Addr_ProvinceID, value);
                this._Addr_ProvinceID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Addr_Province
        {
            get { return _Addr_Province; }
            set
            {
                this.OnPropertyValueChange(_.Addr_Province, _Addr_Province, value);
                this._Addr_Province = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Addr_Street
        {
            get { return _Addr_Street; }
            set
            {
                this.OnPropertyValueChange(_.Addr_Street, _Addr_Street, value);
                this._Addr_Street = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Address
        {
            get { return _Address; }
            set
            {
                this.OnPropertyValueChange(_.Address, _Address, value);
                this._Address = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PostalCode
        {
            get { return _PostalCode; }
            set
            {
                this.OnPropertyValueChange(_.PostalCode, _PostalCode, value);
                this._PostalCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Wp_Url
        {
            get { return _Wp_Url; }
            set
            {
                this.OnPropertyValueChange(_.Wp_Url, _Wp_Url, value);
                this._Wp_Url = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? WP_TemplateID
        {
            get { return _WP_TemplateID; }
            set
            {
                this.OnPropertyValueChange(_.WP_TemplateID, _WP_TemplateID, value);
                this._WP_TemplateID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Wp_Config
        {
            get { return _Wp_Config; }
            set
            {
                this.OnPropertyValueChange(_.Wp_Config, _Wp_Config, value);
                this._Wp_Config = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Wp_Banner
        {
            get { return _Wp_Banner; }
            set
            {
                this.OnPropertyValueChange(_.Wp_Banner, _Wp_Banner, value);
                this._Wp_Banner = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CompanyName
        {
            get { return _CompanyName; }
            set
            {
                this.OnPropertyValueChange(_.CompanyName, _CompanyName, value);
                this._CompanyName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CompanyPic
        {
            get { return _CompanyPic; }
            set
            {
                this.OnPropertyValueChange(_.CompanyPic, _CompanyPic, value);
                this._CompanyPic = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string BusinessTypeID
        {
            get { return _BusinessTypeID; }
            set
            {
                this.OnPropertyValueChange(_.BusinessTypeID, _BusinessTypeID, value);
                this._BusinessTypeID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string BusinessType
        {
            get { return _BusinessType; }
            set
            {
                this.OnPropertyValueChange(_.BusinessType, _BusinessType, value);
                this._BusinessType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ProductService_Sell
        {
            get { return _ProductService_Sell; }
            set
            {
                this.OnPropertyValueChange(_.ProductService_Sell, _ProductService_Sell, value);
                this._ProductService_Sell = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ProductService_Buy
        {
            get { return _ProductService_Buy; }
            set
            {
                this.OnPropertyValueChange(_.ProductService_Buy, _ProductService_Buy, value);
                this._ProductService_Buy = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? CompanyRegistered
        {
            get { return _CompanyRegistered; }
            set
            {
                this.OnPropertyValueChange(_.CompanyRegistered, _CompanyRegistered, value);
                this._CompanyRegistered = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string TotalEmployees
        {
            get { return _TotalEmployees; }
            set
            {
                this.OnPropertyValueChange(_.TotalEmployees, _TotalEmployees, value);
                this._TotalEmployees = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Logo
        {
            get { return _Logo; }
            set
            {
                this.OnPropertyValueChange(_.Logo, _Logo, value);
                this._Logo = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Introduction
        {
            get { return _Introduction; }
            set
            {
                this.OnPropertyValueChange(_.Introduction, _Introduction, value);
                this._Introduction = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string WebsiteUrl
        {
            get { return _WebsiteUrl; }
            set
            {
                this.OnPropertyValueChange(_.WebsiteUrl, _WebsiteUrl, value);
                this._WebsiteUrl = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Brands
        {
            get { return _Brands; }
            set
            {
                this.OnPropertyValueChange(_.Brands, _Brands, value);
                this._Brands = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string LegalForm
        {
            get { return _LegalForm; }
            set
            {
                this.OnPropertyValueChange(_.LegalForm, _LegalForm, value);
                this._LegalForm = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string LegalOwner
        {
            get { return _LegalOwner; }
            set
            {
                this.OnPropertyValueChange(_.LegalOwner, _LegalOwner, value);
                this._LegalOwner = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string LegalCEO
        {
            get { return _LegalCEO; }
            set
            {
                this.OnPropertyValueChange(_.LegalCEO, _LegalCEO, value);
                this._LegalCEO = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string OperationalAddressType
        {
            get { return _OperationalAddressType; }
            set
            {
                this.OnPropertyValueChange(_.OperationalAddressType, _OperationalAddressType, value);
                this._OperationalAddressType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string OwnershipType
        {
            get { return _OwnershipType; }
            set
            {
                this.OnPropertyValueChange(_.OwnershipType, _OwnershipType, value);
                this._OwnershipType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string RegisteredCapital
        {
            get { return _RegisteredCapital; }
            set
            {
                this.OnPropertyValueChange(_.RegisteredCapital, _RegisteredCapital, value);
                this._RegisteredCapital = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string TotalAnnualSalesVolume
        {
            get { return _TotalAnnualSalesVolume; }
            set
            {
                this.OnPropertyValueChange(_.TotalAnnualSalesVolume, _TotalAnnualSalesVolume, value);
                this._TotalAnnualSalesVolume = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string TotalAnnualPurchaseVolume
        {
            get { return _TotalAnnualPurchaseVolume; }
            set
            {
                this.OnPropertyValueChange(_.TotalAnnualPurchaseVolume, _TotalAnnualPurchaseVolume, value);
                this._TotalAnnualPurchaseVolume = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ExportPercentage
        {
            get { return _ExportPercentage; }
            set
            {
                this.OnPropertyValueChange(_.ExportPercentage, _ExportPercentage, value);
                this._ExportPercentage = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MainMarkets
        {
            get { return _MainMarkets; }
            set
            {
                this.OnPropertyValueChange(_.MainMarkets, _MainMarkets, value);
                this._MainMarkets = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MainCustomers
        {
            get { return _MainCustomers; }
            set
            {
                this.OnPropertyValueChange(_.MainCustomers, _MainCustomers, value);
                this._MainCustomers = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string TradeShows
        {
            get { return _TradeShows; }
            set
            {
                this.OnPropertyValueChange(_.TradeShows, _TradeShows, value);
                this._TradeShows = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ContractManufacturing
        {
            get { return _ContractManufacturing; }
            set
            {
                this.OnPropertyValueChange(_.ContractManufacturing, _ContractManufacturing, value);
                this._ContractManufacturing = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string FactorySize
        {
            get { return _FactorySize; }
            set
            {
                this.OnPropertyValueChange(_.FactorySize, _FactorySize, value);
                this._FactorySize = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string FactoryLocation
        {
            get { return _FactoryLocation; }
            set
            {
                this.OnPropertyValueChange(_.FactoryLocation, _FactoryLocation, value);
                this._FactoryLocation = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? BuiltYear
        {
            get { return _BuiltYear; }
            set
            {
                this.OnPropertyValueChange(_.BuiltYear, _BuiltYear, value);
                this._BuiltYear = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ProductRange
        {
            get { return _ProductRange; }
            set
            {
                this.OnPropertyValueChange(_.ProductRange, _ProductRange, value);
                this._ProductRange = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string MonthlyCapacity
        {
            get { return _MonthlyCapacity; }
            set
            {
                this.OnPropertyValueChange(_.MonthlyCapacity, _MonthlyCapacity, value);
                this._MonthlyCapacity = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string QAQC
        {
            get { return _QAQC; }
            set
            {
                this.OnPropertyValueChange(_.QAQC, _QAQC, value);
                this._QAQC = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string NoofProductionLines
        {
            get { return _NoofProductionLines; }
            set
            {
                this.OnPropertyValueChange(_.NoofProductionLines, _NoofProductionLines, value);
                this._NoofProductionLines = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string NoofRDStaff
        {
            get { return _NoofRDStaff; }
            set
            {
                this.OnPropertyValueChange(_.NoofRDStaff, _NoofRDStaff, value);
                this._NoofRDStaff = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string NoofQCStaff
        {
            get { return _NoofQCStaff; }
            set
            {
                this.OnPropertyValueChange(_.NoofQCStaff, _NoofQCStaff, value);
                this._NoofQCStaff = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ManagementCertification
        {
            get { return _ManagementCertification; }
            set
            {
                this.OnPropertyValueChange(_.ManagementCertification, _ManagementCertification, value);
                this._ManagementCertification = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? RegTime
        {
            get { return _RegTime; }
            set
            {
                this.OnPropertyValueChange(_.RegTime, _RegTime, value);
                this._RegTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? LoginNums
        {
            get { return _LoginNums; }
            set
            {
                this.OnPropertyValueChange(_.LoginNums, _LoginNums, value);
                this._LoginNums = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? LoginTime
        {
            get { return _LoginTime; }
            set
            {
                this.OnPropertyValueChange(_.LoginTime, _LoginTime, value);
                this._LoginTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string LoginIp
        {
            get { return _LoginIp; }
            set
            {
                this.OnPropertyValueChange(_.LoginIp, _LoginIp, value);
                this._LoginIp = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool? IsGather
        {
            get { return _IsGather; }
            set
            {
                this.OnPropertyValueChange(_.IsGather, _IsGather, value);
                this._IsGather = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? UserType
        {
            get { return _UserType; }
            set
            {
                this.OnPropertyValueChange(_.UserType, _UserType, value);
                this._UserType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Grade
        {
            get { return _Grade; }
            set
            {
                this.OnPropertyValueChange(_.Grade, _Grade, value);
                this._Grade = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Type
        {
            get { return _Type; }
            set
            {
                this.OnPropertyValueChange(_.Type, _Type, value);
                this._Type = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? EmailStatus
        {
            get { return _EmailStatus; }
            set
            {
                this.OnPropertyValueChange(_.EmailStatus, _EmailStatus, value);
                this._EmailStatus = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? WebsiteUrlStatus
        {
            get { return _WebsiteUrlStatus; }
            set
            {
                this.OnPropertyValueChange(_.WebsiteUrlStatus, _WebsiteUrlStatus, value);
                this._WebsiteUrlStatus = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? ProductStatus
        {
            get { return _ProductStatus; }
            set
            {
                this.OnPropertyValueChange(_.ProductStatus, _ProductStatus, value);
                this._ProductStatus = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? EditAdminId
        {
            get { return _EditAdminId; }
            set
            {
                this.OnPropertyValueChange(_.EditAdminId, _EditAdminId, value);
                this._EditAdminId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? EditTime
        {
            get { return _EditTime; }
            set
            {
                this.OnPropertyValueChange(_.EditTime, _EditTime, value);
                this._EditTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Status
        {
            get { return _Status; }
            set
            {
                this.OnPropertyValueChange(_.Status, _Status, value);
                this._Status = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? IndustryType
        {
            get { return _IndustryType; }
            set
            {
                this.OnPropertyValueChange(_.IndustryType, _IndustryType, value);
                this._IndustryType = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Stock_Id
        {
            get { return _Stock_Id; }
            set
            {
                this.OnPropertyValueChange(_.Stock_Id, _Stock_Id, value);
                this._Stock_Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? AdminId
        {
            get { return _AdminId; }
            set
            {
                this.OnPropertyValueChange(_.AdminId, _AdminId, value);
                this._AdminId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? UserLevel
        {
            get { return _UserLevel; }
            set
            {
                this.OnPropertyValueChange(_.UserLevel, _UserLevel, value);
                this._UserLevel = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? KeywordsNum
        {
            get { return _KeywordsNum; }
            set
            {
                this.OnPropertyValueChange(_.KeywordsNum, _KeywordsNum, value);
                this._KeywordsNum = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? UsekeywordsNum
        {
            get { return _UsekeywordsNum; }
            set
            {
                this.OnPropertyValueChange(_.UsekeywordsNum, _UsekeywordsNum, value);
                this._UsekeywordsNum = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? UserProductCount
        {
            get { return _UserProductCount; }
            set
            {
                this.OnPropertyValueChange(_.UserProductCount, _UserProductCount, value);
                this._UserProductCount = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Certification
        {
            get { return _Certification; }
            set
            {
                this.OnPropertyValueChange(_.Certification, _Certification, value);
                this._Certification = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Licence
        {
            get { return _Licence; }
            set
            {
                this.OnPropertyValueChange(_.Licence, _Licence, value);
                this._Licence = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? BaseAuditedStatus
        {
            get { return _BaseAuditedStatus; }
            set
            {
                this.OnPropertyValueChange(_.BaseAuditedStatus, _BaseAuditedStatus, value);
                this._BaseAuditedStatus = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string BaseAuditedCode
        {
            get { return _BaseAuditedCode; }
            set
            {
                this.OnPropertyValueChange(_.BaseAuditedCode, _BaseAuditedCode, value);
                this._BaseAuditedCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? ThirdPartyAuditedStatus
        {
            get { return _ThirdPartyAuditedStatus; }
            set
            {
                this.OnPropertyValueChange(_.ThirdPartyAuditedStatus, _ThirdPartyAuditedStatus, value);
                this._ThirdPartyAuditedStatus = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ThirdPartyAuditedCode
        {
            get { return _ThirdPartyAuditedCode; }
            set
            {
                this.OnPropertyValueChange(_.ThirdPartyAuditedCode, _ThirdPartyAuditedCode, value);
                this._ThirdPartyAuditedCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool? IsModified
        {
            get { return _IsModified; }
            set
            {
                this.OnPropertyValueChange(_.IsModified, _IsModified, value);
                this._IsModified = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ModifyCode
        {
            get { return _ModifyCode; }
            set
            {
                this.OnPropertyValueChange(_.ModifyCode, _ModifyCode, value);
                this._ModifyCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string InfoCompletedCode
        {
            get { return _InfoCompletedCode; }
            set
            {
                this.OnPropertyValueChange(_.InfoCompletedCode, _InfoCompletedCode, value);
                this._InfoCompletedCode = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? AuditedTime
        {
            get { return _AuditedTime; }
            set
            {
                this.OnPropertyValueChange(_.AuditedTime, _AuditedTime, value);
                this._AuditedTime = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? CheckDate
        {
            get { return _CheckDate; }
            set
            {
                this.OnPropertyValueChange(_.CheckDate, _CheckDate, value);
                this._CheckDate = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Reason
        {
            get { return _Reason; }
            set
            {
                this.OnPropertyValueChange(_.Reason, _Reason, value);
                this._Reason = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public float? Boost
        {
            get { return _Boost; }
            set
            {
                this.OnPropertyValueChange(_.Boost, _Boost, value);
                this._Boost = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public float? BoostOrder
        {
            get { return _BoostOrder; }
            set
            {
                this.OnPropertyValueChange(_.BoostOrder, _BoostOrder, value);
                this._BoostOrder = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Contact_Address
        {
            get { return _Contact_Address; }
            set
            {
                this.OnPropertyValueChange(_.Contact_Address, _Contact_Address, value);
                this._Contact_Address = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? InquiryLimit
        {
            get { return _InquiryLimit; }
            set
            {
                this.OnPropertyValueChange(_.InquiryLimit, _InquiryLimit, value);
                this._InquiryLimit = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? InquiryLimitUse
        {
            get { return _InquiryLimitUse; }
            set
            {
                this.OnPropertyValueChange(_.InquiryLimitUse, _InquiryLimitUse, value);
                this._InquiryLimitUse = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? GatherId
        {
            get { return _GatherId; }
            set
            {
                this.OnPropertyValueChange(_.GatherId, _GatherId, value);
                this._GatherId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ProductionFlowPic
        {
            get { return _ProductionFlowPic; }
            set
            {
                this.OnPropertyValueChange(_.ProductionFlowPic, _ProductionFlowPic, value);
                this._ProductionFlowPic = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id};
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.FirstName,
                _.LastName,
                _.Gender,
                _.ContactPic,
                _.UserName,
                _.Psw,
                _.Email,
                _.Tel,
                _.Fax,
                _.Mobile,
                _.WhatsApp,
                _.Skype,
                _.Department,
                _.Job,
                _.Addr_CountryID,
                _.Addr_Country,
                _.Addr_ProvinceID,
                _.Addr_Province,
                _.Addr_Street,
                _.Address,
                _.PostalCode,
                _.Wp_Url,
                _.WP_TemplateID,
                _.Wp_Config,
                _.Wp_Banner,
                _.CompanyName,
                _.CompanyPic,
                _.BusinessTypeID,
                _.BusinessType,
                _.ProductService_Sell,
                _.ProductService_Buy,
                _.CompanyRegistered,
                _.TotalEmployees,
                _.Logo,
                _.Introduction,
                _.WebsiteUrl,
                _.Brands,
                _.LegalForm,
                _.LegalOwner,
                _.LegalCEO,
                _.OperationalAddressType,
                _.OwnershipType,
                _.RegisteredCapital,
                _.TotalAnnualSalesVolume,
                _.TotalAnnualPurchaseVolume,
                _.ExportPercentage,
                _.MainMarkets,
                _.MainCustomers,
                _.TradeShows,
                _.ContractManufacturing,
                _.FactorySize,
                _.FactoryLocation,
                _.BuiltYear,
                _.ProductRange,
                _.MonthlyCapacity,
                _.QAQC,
                _.NoofProductionLines,
                _.NoofRDStaff,
                _.NoofQCStaff,
                _.ManagementCertification,
                _.RegTime,
                _.LoginNums,
                _.LoginTime,
                _.LoginIp,
                _.IsGather,
                _.UserType,
                _.Grade,
                _.Type,
                _.EmailStatus,
                _.WebsiteUrlStatus,
                _.ProductStatus,
                _.EditAdminId,
                _.EditTime,
                _.Status,
                _.IndustryType,
                _.Stock_Id,
                _.AdminId,
                _.UserLevel,
                _.KeywordsNum,
                _.UsekeywordsNum,
                _.UserProductCount,
                _.Certification,
                _.Licence,
                _.BaseAuditedStatus,
                _.BaseAuditedCode,
                _.ThirdPartyAuditedStatus,
                _.ThirdPartyAuditedCode,
                _.IsModified,
                _.ModifyCode,
                _.InfoCompletedCode,
                _.AuditedTime,
                _.CheckDate,
                _.Reason,
                _.Boost,
                _.BoostOrder,
                _.Contact_Address,
                _.InquiryLimit,
                _.InquiryLimitUse,
                _.GatherId,
                _.ProductionFlowPic};
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._FirstName,
                this._LastName,
                this._Gender,
                this._ContactPic,
                this._UserName,
                this._Psw,
                this._Email,
                this._Tel,
                this._Fax,
                this._Mobile,
                this._WhatsApp,
                this._Skype,
                this._Department,
                this._Job,
                this._Addr_CountryID,
                this._Addr_Country,
                this._Addr_ProvinceID,
                this._Addr_Province,
                this._Addr_Street,
                this._Address,
                this._PostalCode,
                this._Wp_Url,
                this._WP_TemplateID,
                this._Wp_Config,
                this._Wp_Banner,
                this._CompanyName,
                this._CompanyPic,
                this._BusinessTypeID,
                this._BusinessType,
                this._ProductService_Sell,
                this._ProductService_Buy,
                this._CompanyRegistered,
                this._TotalEmployees,
                this._Logo,
                this._Introduction,
                this._WebsiteUrl,
                this._Brands,
                this._LegalForm,
                this._LegalOwner,
                this._LegalCEO,
                this._OperationalAddressType,
                this._OwnershipType,
                this._RegisteredCapital,
                this._TotalAnnualSalesVolume,
                this._TotalAnnualPurchaseVolume,
                this._ExportPercentage,
                this._MainMarkets,
                this._MainCustomers,
                this._TradeShows,
                this._ContractManufacturing,
                this._FactorySize,
                this._FactoryLocation,
                this._BuiltYear,
                this._ProductRange,
                this._MonthlyCapacity,
                this._QAQC,
                this._NoofProductionLines,
                this._NoofRDStaff,
                this._NoofQCStaff,
                this._ManagementCertification,
                this._RegTime,
                this._LoginNums,
                this._LoginTime,
                this._LoginIp,
                this._IsGather,
                this._UserType,
                this._Grade,
                this._Type,
                this._EmailStatus,
                this._WebsiteUrlStatus,
                this._ProductStatus,
                this._EditAdminId,
                this._EditTime,
                this._Status,
                this._IndustryType,
                this._Stock_Id,
                this._AdminId,
                this._UserLevel,
                this._KeywordsNum,
                this._UsekeywordsNum,
                this._UserProductCount,
                this._Certification,
                this._Licence,
                this._BaseAuditedStatus,
                this._BaseAuditedCode,
                this._ThirdPartyAuditedStatus,
                this._ThirdPartyAuditedCode,
                this._IsModified,
                this._ModifyCode,
                this._InfoCompletedCode,
                this._AuditedTime,
                this._CheckDate,
                this._Reason,
                this._Boost,
                this._BoostOrder,
                this._Contact_Address,
                this._InquiryLimit,
                this._InquiryLimitUse,
                this._GatherId,
                this._ProductionFlowPic};
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "User_Info");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Id = new Field("Id", "User_Info", "Id");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field FirstName = new Field("FirstName", "User_Info", "FirstName");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field LastName = new Field("LastName", "User_Info", "LastName");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Gender = new Field("Gender", "User_Info", "Gender");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ContactPic = new Field("ContactPic", "User_Info", "ContactPic");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UserName = new Field("UserName", "User_Info", "UserName");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Psw = new Field("Psw", "User_Info", "Psw");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Email = new Field("Email", "User_Info", "Email");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Tel = new Field("Tel", "User_Info", "Tel");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Fax = new Field("Fax", "User_Info", "Fax");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Mobile = new Field("Mobile", "User_Info", "Mobile");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field WhatsApp = new Field("WhatsApp", "User_Info", "WhatsApp");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Skype = new Field("Skype", "User_Info", "Skype");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Department = new Field("Department", "User_Info", "Department");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Job = new Field("Job", "User_Info", "Job");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Addr_CountryID = new Field("Addr_CountryID", "User_Info", "Addr_CountryID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Addr_Country = new Field("Addr_Country", "User_Info", "Addr_Country");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Addr_ProvinceID = new Field("Addr_ProvinceID", "User_Info", "Addr_ProvinceID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Addr_Province = new Field("Addr_Province", "User_Info", "Addr_Province");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Addr_Street = new Field("Addr_Street", "User_Info", "Addr_Street");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Address = new Field("Address", "User_Info", "Address");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field PostalCode = new Field("PostalCode", "User_Info", "PostalCode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Wp_Url = new Field("Wp_Url", "User_Info", "Wp_Url");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field WP_TemplateID = new Field("WP_TemplateID", "User_Info", "WP_TemplateID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Wp_Config = new Field("Wp_Config", "User_Info", "Wp_Config");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Wp_Banner = new Field("Wp_Banner", "User_Info", "Wp_Banner");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CompanyName = new Field("CompanyName", "User_Info", "CompanyName");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CompanyPic = new Field("CompanyPic", "User_Info", "CompanyPic");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field BusinessTypeID = new Field("BusinessTypeID", "User_Info", "BusinessTypeID");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field BusinessType = new Field("BusinessType", "User_Info", "BusinessType");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ProductService_Sell = new Field("ProductService_Sell", "User_Info", "ProductService_Sell");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ProductService_Buy = new Field("ProductService_Buy", "User_Info", "ProductService_Buy");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CompanyRegistered = new Field("CompanyRegistered", "User_Info", "CompanyRegistered");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field TotalEmployees = new Field("TotalEmployees", "User_Info", "TotalEmployees");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Logo = new Field("Logo", "User_Info", "Logo");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Introduction = new Field("Introduction", "User_Info", "Introduction");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field WebsiteUrl = new Field("WebsiteUrl", "User_Info", "WebsiteUrl");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Brands = new Field("Brands", "User_Info", "Brands");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field LegalForm = new Field("LegalForm", "User_Info", "LegalForm");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field LegalOwner = new Field("LegalOwner", "User_Info", "LegalOwner");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field LegalCEO = new Field("LegalCEO", "User_Info", "LegalCEO");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field OperationalAddressType = new Field("OperationalAddressType", "User_Info", "OperationalAddressType");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field OwnershipType = new Field("OwnershipType", "User_Info", "OwnershipType");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RegisteredCapital = new Field("RegisteredCapital", "User_Info", "RegisteredCapital");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field TotalAnnualSalesVolume = new Field("TotalAnnualSalesVolume", "User_Info", "TotalAnnualSalesVolume");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field TotalAnnualPurchaseVolume = new Field("TotalAnnualPurchaseVolume", "User_Info", "TotalAnnualPurchaseVolume");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ExportPercentage = new Field("ExportPercentage", "User_Info", "ExportPercentage");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MainMarkets = new Field("MainMarkets", "User_Info", "MainMarkets");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MainCustomers = new Field("MainCustomers", "User_Info", "MainCustomers");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field TradeShows = new Field("TradeShows", "User_Info", "TradeShows");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ContractManufacturing = new Field("ContractManufacturing", "User_Info", "ContractManufacturing");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field FactorySize = new Field("FactorySize", "User_Info", "FactorySize");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field FactoryLocation = new Field("FactoryLocation", "User_Info", "FactoryLocation");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field BuiltYear = new Field("BuiltYear", "User_Info", "BuiltYear");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ProductRange = new Field("ProductRange", "User_Info", "ProductRange");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field MonthlyCapacity = new Field("MonthlyCapacity", "User_Info", "MonthlyCapacity");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field QAQC = new Field("QAQC", "User_Info", "QAQC");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field NoofProductionLines = new Field("NoofProductionLines", "User_Info", "NoofProductionLines");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field NoofRDStaff = new Field("NoofRDStaff", "User_Info", "NoofRDStaff");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field NoofQCStaff = new Field("NoofQCStaff", "User_Info", "NoofQCStaff");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ManagementCertification = new Field("ManagementCertification", "User_Info", "ManagementCertification");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field RegTime = new Field("RegTime", "User_Info", "RegTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field LoginNums = new Field("LoginNums", "User_Info", "LoginNums");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field LoginTime = new Field("LoginTime", "User_Info", "LoginTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field LoginIp = new Field("LoginIp", "User_Info", "LoginIp");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IsGather = new Field("IsGather", "User_Info", "IsGather");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UserType = new Field("UserType", "User_Info", "UserType");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Grade = new Field("Grade", "User_Info", "Grade");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Type = new Field("Type", "User_Info", "Type");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field EmailStatus = new Field("EmailStatus", "User_Info", "EmailStatus");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field WebsiteUrlStatus = new Field("WebsiteUrlStatus", "User_Info", "WebsiteUrlStatus");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ProductStatus = new Field("ProductStatus", "User_Info", "ProductStatus");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field EditAdminId = new Field("EditAdminId", "User_Info", "EditAdminId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field EditTime = new Field("EditTime", "User_Info", "EditTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Status = new Field("Status", "User_Info", "Status");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IndustryType = new Field("IndustryType", "User_Info", "IndustryType");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Stock_Id = new Field("Stock_Id", "User_Info", "Stock_Id");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field AdminId = new Field("AdminId", "User_Info", "AdminId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UserLevel = new Field("UserLevel", "User_Info", "UserLevel");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field KeywordsNum = new Field("KeywordsNum", "User_Info", "KeywordsNum");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UsekeywordsNum = new Field("UsekeywordsNum", "User_Info", "UsekeywordsNum");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field UserProductCount = new Field("UserProductCount", "User_Info", "UserProductCount");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Certification = new Field("Certification", "User_Info", "Certification");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Licence = new Field("Licence", "User_Info", "Licence");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field BaseAuditedStatus = new Field("BaseAuditedStatus", "User_Info", "BaseAuditedStatus");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field BaseAuditedCode = new Field("BaseAuditedCode", "User_Info", "BaseAuditedCode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ThirdPartyAuditedStatus = new Field("ThirdPartyAuditedStatus", "User_Info", "ThirdPartyAuditedStatus");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ThirdPartyAuditedCode = new Field("ThirdPartyAuditedCode", "User_Info", "ThirdPartyAuditedCode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field IsModified = new Field("IsModified", "User_Info", "IsModified");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ModifyCode = new Field("ModifyCode", "User_Info", "ModifyCode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field InfoCompletedCode = new Field("InfoCompletedCode", "User_Info", "InfoCompletedCode");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field AuditedTime = new Field("AuditedTime", "User_Info", "AuditedTime");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field CheckDate = new Field("CheckDate", "User_Info", "CheckDate");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Reason = new Field("Reason", "User_Info", "Reason");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Boost = new Field("Boost", "User_Info", "Boost");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field BoostOrder = new Field("BoostOrder", "User_Info", "BoostOrder");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field Contact_Address = new Field("Contact_Address", "User_Info", "Contact_Address");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field InquiryLimit = new Field("InquiryLimit", "User_Info", "InquiryLimit");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field InquiryLimitUse = new Field("InquiryLimitUse", "User_Info", "InquiryLimitUse");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field GatherId = new Field("GatherId", "User_Info", "GatherId");
            /// <summary>
            /// 
            /// </summary>
            public readonly static Field ProductionFlowPic = new Field("ProductionFlowPic", "User_Info", "ProductionFlowPic");
        }
        #endregion


    }
}

