//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dos.ORM;

namespace WebGather.Model
{
    /// <summary>
    /// 实体类Video_Class。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Video_Class")]
    [Serializable]
    public partial class Video_Class : Entity
    {
        #region Model
        private int _Id;
        private int? _ParId;
        private string _ClassName;
        private int? _Sequence;
        private int? _Depth;
        private int? _ChildNum;
        private string _ParPath;
        private bool? _BeLock;
        private int _Hits;
        private int _VideoCnt;

        /// <summary>
        /// 
        /// </summary>
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? ParId
        {
            get { return _ParId; }
            set
            {
                this.OnPropertyValueChange("ParId");
                this._ParId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ClassName
        {
            get { return _ClassName; }
            set
            {
                this.OnPropertyValueChange("ClassName");
                this._ClassName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Sequence
        {
            get { return _Sequence; }
            set
            {
                this.OnPropertyValueChange("Sequence");
                this._Sequence = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? Depth
        {
            get { return _Depth; }
            set
            {
                this.OnPropertyValueChange("Depth");
                this._Depth = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int? ChildNum
        {
            get { return _ChildNum; }
            set
            {
                this.OnPropertyValueChange("ChildNum");
                this._ChildNum = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ParPath
        {
            get { return _ParPath; }
            set
            {
                this.OnPropertyValueChange("ParPath");
                this._ParPath = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool? BeLock
        {
            get { return _BeLock; }
            set
            {
                this.OnPropertyValueChange("BeLock");
                this._BeLock = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int Hits
        {
            get { return _Hits; }
            set
            {
                this.OnPropertyValueChange("Hits");
                this._Hits = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int VideoCnt
        {
            get { return _VideoCnt; }
            set
            {
                this.OnPropertyValueChange("VideoCnt");
                this._VideoCnt = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.ParId,
                _.ClassName,
                _.Sequence,
                _.Depth,
                _.ChildNum,
                _.ParPath,
                _.BeLock,
                _.Hits,
                _.VideoCnt,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._ParId,
                this._ClassName,
                this._Sequence,
                this._Depth,
                this._ChildNum,
                this._ParPath,
                this._BeLock,
                this._Hits,
                this._VideoCnt,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*", "Video_Class");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id", "Video_Class", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ParId = new Field("ParId", "Video_Class", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ClassName = new Field("ClassName", "Video_Class", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Sequence = new Field("Sequence", "Video_Class", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Depth = new Field("Depth", "Video_Class", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ChildNum = new Field("ChildNum", "Video_Class", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ParPath = new Field("ParPath", "Video_Class", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field BeLock = new Field("BeLock", "Video_Class", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Hits = new Field("Hits", "Video_Class", "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field VideoCnt = new Field("VideoCnt", "Video_Class", "");
        }
        #endregion
    }
}